name: Terraform Apply (dev)

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  apply-dev:
    name: Apply to dev workspace
    runs-on: ubuntu-latest
    env:
        TF_VAR_project_name: "stark-industries"
        TF_VAR_count_of_instances: "1"
        TF_VAR_ami_type: "ubuntu_2204"
        TF_VAR_instance_type: "t3.micro"
        TF_VAR_associate_public_ip_address: "true"
        TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
        TF_VAR_api_stage_name: "dev"
        TF_VAR_alert_email: "stark@gmail.com"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform -chdir=stark_industries init -input=false

      - name: Select workspace dev
        run: |
          terraform -chdir=stark_industries workspace select dev || terraform -chdir=stark_industries workspace new dev

      - name: Terraform apply
        run: terraform -chdir=stark_industries apply -auto-approve
