name: Terraform Pull Request Check

on:
  pull_request:
    branches:
      - dev
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  tf-pr-check:
    runs-on: ubuntu-latest
    env:
        TF_VAR_alert_email: "stark@gmail.com"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
       

      # ---------- Terraform Checks (NO APPLY) ----------

      - name: Terraform Init
        run: terraform -chdir=stark_industries init

      - name: Terraform Format Check
        run: terraform -chdir=stark_industries fmt -check -recursive

      - name: Terraform Validate
        run: terraform -chdir=stark_industries validate

      - name: Select correct workspace based on target branch
        id: ws
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "workspace=prod" >> $GITHUB_OUTPUT
          else
            echo "workspace=dev" >> $GITHUB_OUTPUT
          fi

      - name: Select or create workspace
        run: |
          terraform -chdir=stark_industries workspace select ${{ steps.ws.outputs.workspace }} \
          || terraform -chdir=stark_industries workspace new ${{ steps.ws.outputs.workspace }}

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=stark_industries plan -no-color
        continue-on-error: true

      # ---------- Comment PLAN on Pull Request ----------
      - name: Comment Terraform Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: terraform-plan
          message: |
            ## Terraform Plan Result
            Workspace: **${{ steps.ws.outputs.workspace }}**

            ```
            ${{ steps.plan.outputs.stdout }}
            ```
