name: Terraform Apply (prod)

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  apply-prod:
    name: Apply to prod workspace
    runs-on: ubuntu-latest
    environment: 
      name: prod   # configure this environment in repo settings and add required reviewers
    env:
        TF_VAR_alert_email: "stark@gmail.com"
        TF_VAR_ami_type: "ubuntu_2204"
        TF_VAR_instance_type: "t3.micro"
        TF_VAR_vpc_id: ${{ secrets.VPC_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform -chdir=stark_industries init -input=false

      - name: Select workspace prod
        run: |
          terraform -chdir=stark_industries workspace select prod || terraform -chdir=stark_industries workspace new prod

      - name: Terraform apply to prod
        run: terraform -chdir=stark_industries apply -auto-approve