name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to destroy"
        type: choice
        required: true
        options:
          - dev
          - prod

permissions:
  contents: read

jobs:
  destroy:
    name: Destroy ${{ github.event.inputs.environment }} workspace
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_name: "stark-industries"
      TF_VAR_count_of_instances: "1"
      TF_VAR_ami_type: "ubuntu_2204"
      TF_VAR_instance_type: "t3.micro"
      TF_VAR_associate_public_ip_address: "true"
      TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
      TF_VAR_api_stage_name: ${{ github.event.inputs.environment }}
      TF_VAR_alert_email: "stark@gmail.com"

    steps:
      - name: ğŸš€ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ” Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ğŸ“¦ Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: ğŸ—ï¸ Terraform Init
        run: terraform -chdir=stark_industries init -input=false

      - name: ğŸ”€ Select Workspace
        run: |
          terraform -chdir=stark_industries workspace select ${{ github.event.inputs.environment }} \
          || terraform -chdir=stark_industries workspace new ${{ github.event.inputs.environment }}

      - name: ğŸ’£ Destroy Environment
        run: terraform -chdir=stark_industries destroy -auto-approve
